---
name: HTML-Template-Compiled-Plugin-HTML_Tags
version: 0.01
author: ~
abstract: HTC-Plugin for various HTML tags
license: perl
requires:
  HTML::Template::Compiled: 0.81
provides:
  HTML::Template::Compiled::Plugin::HTML_Tags:
    file: lib/HTML/Template/Compiled/Plugin/HTML_Tags.pm
    version: 0.01
generated_by: Module::Build version 0.2611
